### ISSUE TITLE
@conda-forge-admin, please add user @NikhilJArora

### ISSUE THREAD

**Issue by fdosani** [conda-forge/datacompy-feedstock#23]

**Comment by fdosani** [comment]
@conda-forge/core Can you please assist here? @NikhilJArora is part of the recipe, but not included in the [team](https://github.com/orgs/conda-forge/teams/datacompy). He doesn't seem to have an invitation which he can accept either.

**Comment by jakirkham** [comment]
Sounds like this got resolved eventually? See you on the team

<img width="1326" alt="Screenshot 2023-07-19 at 2 08 16 PM" src="https://github.com/conda-forge/datacompy-feedstock/assets/3019665/828385b7-c4cc-478d-905d-8725a1c7bd31">

**Comment by fdosani** [comment]
@jakirkham yea sorry about that. We just removed and re added. Thank you though for checking
